//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleTest {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class VFormResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VFormResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScheduleTest.VFormResource", typeof(VFormResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 255, 255, 255.
        /// </summary>
        internal static string AppointmentColor {
            get {
                return ResourceManager.GetString("AppointmentColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 189,215, 176.
        /// </summary>
        internal static string AvailableHourBackGroundColor {
            get {
                return ResourceManager.GetString("AvailableHourBackGroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 255, 255, 255.
        /// </summary>
        internal static string BackColorForNormalField {
            get {
                return ResourceManager.GetString("BackColorForNormalField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 245,160,75.
        /// </summary>
        internal static string BackColorForRequiredField {
            get {
                return ResourceManager.GetString("BackColorForRequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 213, 220, 228.
        /// </summary>
        internal static string BackColorNormal {
            get {
                return ResourceManager.GetString("BackColorNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have entered one or more unrecognized characters..
        /// </summary>
        internal static string BadTextInput {
            get {
                return ResourceManager.GetString("BadTextInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segoe UI, 8, regular.
        /// </summary>
        internal static string ButtonFont {
            get {
                return ResourceManager.GetString("ButtonFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 246, 133, 86.
        /// </summary>
        internal static string ControlHighLightColor {
            get {
                return ResourceManager.GetString("ControlHighLightColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 227, 231, 236.
        /// </summary>
        internal static string DisabledColor {
            get {
                return ResourceManager.GetString("DisabledColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segoe UI, 8, regular.
        /// </summary>
        internal static string Font {
            get {
                return ResourceManager.GetString("Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 197, 194,118.
        /// </summary>
        internal static string HolidayBackGroundColor {
            get {
                return ResourceManager.GetString("HolidayBackGroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 197, 194,118.
        /// </summary>
        internal static string HourBackGroundColor {
            get {
                return ResourceManager.GetString("HourBackGroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 222,234,248.
        /// </summary>
        internal static string JanusDataGridAlternatingRowBackColor {
            get {
                return ResourceManager.GetString("JanusDataGridAlternatingRowBackColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 255,255,210.
        /// </summary>
        internal static string JanusDataGridFilterRowBackColor {
            get {
                return ResourceManager.GetString("JanusDataGridFilterRowBackColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,0,153.
        /// </summary>
        internal static string JanusDataGridFilterRowForeColor {
            get {
                return ResourceManager.GetString("JanusDataGridFilterRowForeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segoe UI, 8, Regular.
        /// </summary>
        internal static string JanusDataGridFont {
            get {
                return ResourceManager.GetString("JanusDataGridFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 213,220,228.
        /// </summary>
        internal static string JanusDataGridGroupByBoxBackColor {
            get {
                return ResourceManager.GetString("JanusDataGridGroupByBoxBackColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segoe UI, 8,regular.
        /// </summary>
        internal static string JanusDataGridGroupByBoxFont {
            get {
                return ResourceManager.GetString("JanusDataGridGroupByBoxFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 185,206,230.
        /// </summary>
        internal static string JanusDataGridGroupRowBackColor {
            get {
                return ResourceManager.GetString("JanusDataGridGroupRowBackColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segoe UI, 9, regular.
        /// </summary>
        internal static string JanusDataGridGroupRowFont {
            get {
                return ResourceManager.GetString("JanusDataGridGroupRowFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 213,220,228.
        /// </summary>
        internal static string JanusDataGridGroupTotalRowBackColor {
            get {
                return ResourceManager.GetString("JanusDataGridGroupTotalRowBackColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segoe UI, 8,regular.
        /// </summary>
        internal static string JanusDataGridGroupTotalRowFont {
            get {
                return ResourceManager.GetString("JanusDataGridGroupTotalRowFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 132,132,132.
        /// </summary>
        internal static string JanusDataGridInActiveForeColor {
            get {
                return ResourceManager.GetString("JanusDataGridInActiveForeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 180,255,180.
        /// </summary>
        internal static string JanusDataGridModifiedRowBackColor {
            get {
                return ResourceManager.GetString("JanusDataGridModifiedRowBackColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 240,240,240.
        /// </summary>
        internal static string JanusDataGridPlaceHolderRowBackColor {
            get {
                return ResourceManager.GetString("JanusDataGridPlaceHolderRowBackColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segoe UI, 8,Bold.
        /// </summary>
        internal static string JanusDataGridTitleFont {
            get {
                return ResourceManager.GetString("JanusDataGridTitleFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 42,95,170.
        /// </summary>
        internal static string JanusDataGridTotalRowBackColor {
            get {
                return ResourceManager.GetString("JanusDataGridTotalRowBackColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segoe UI, 9,regular.
        /// </summary>
        internal static string JanusDataGridTotalRowFont {
            get {
                return ResourceManager.GetString("JanusDataGridTotalRowFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segoe UI, 8, regular.
        /// </summary>
        internal static string LabelFont {
            get {
                return ResourceManager.GetString("LabelFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 42, 95, 170.
        /// </summary>
        internal static string LinkLabelColor {
            get {
                return ResourceManager.GetString("LinkLabelColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segoe UI, 10, regular.
        /// </summary>
        internal static string ModernizedFont {
            get {
                return ResourceManager.GetString("ModernizedFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 242, 244, 247.
        /// </summary>
        internal static string MonthBackGroundColor {
            get {
                return ResourceManager.GetString("MonthBackGroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one field must be shown in a view..
        /// </summary>
        internal static string msgAtLeastOneColumnMustBeVisible {
            get {
                return ResourceManager.GetString("msgAtLeastOneColumnMustBeVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 230, 234, 238.
        /// </summary>
        internal static string NonSelectedTabColor {
            get {
                return ResourceManager.GetString("NonSelectedTabColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 213, 220, 228.
        /// </summary>
        internal static string SelectedTabColor {
            get {
                return ResourceManager.GetString("SelectedTabColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segoe UI, 8, Regular.
        /// </summary>
        internal static string StatusBarFont {
            get {
                return ResourceManager.GetString("StatusBarFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string strActive {
            get {
                return ResourceManager.GetString("strActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Item.
        /// </summary>
        internal static string strAddItem {
            get {
                return ResourceManager.GetString("strAddItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amend.
        /// </summary>
        internal static string strAmend {
            get {
                return ResourceManager.GetString("strAmend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        internal static string strApprove {
            get {
                return ResourceManager.GetString("strApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach.
        /// </summary>
        internal static string strAttach {
            get {
                return ResourceManager.GetString("strAttach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string strCancel {
            get {
                return ResourceManager.GetString("strCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column AutoResize.
        /// </summary>
        internal static string strColumnAutoResize {
            get {
                return ResourceManager.GetString("strColumnAutoResize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string strCopy {
            get {
                return ResourceManager.GetString("strCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string strDelete {
            get {
                return ResourceManager.GetString("strDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to document.
        /// </summary>
        internal static string strDocument {
            get {
                return ResourceManager.GetString("strDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string strEdit {
            get {
                return ResourceManager.GetString("strEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text value cannot be all spaces. Enter a valid value.
        /// </summary>
        internal static string strErrMgsAllSpaces {
            get {
                return ResourceManager.GetString("strErrMgsAllSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string strError {
            get {
                return ResourceManager.GetString("strError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading &apos;{0}&apos; Column in grid. Error:{1}..
        /// </summary>
        internal static string strErrorReadingGridColumn {
            get {
                return ResourceManager.GetString("strErrorReadingGridColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string strExport {
            get {
                return ResourceManager.GetString("strExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Chooser.
        /// </summary>
        internal static string strFieldChooserTitle {
            get {
                return ResourceManager.GetString("strFieldChooserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string strFilter {
            get {
                return ResourceManager.GetString("strFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to enter filter criteria.
        /// </summary>
        internal static string strFilterRowInfoText {
            get {
                return ResourceManager.GetString("strFilterRowInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Scaling.
        /// </summary>
        internal static string strFitColNoFit {
            get {
                return ResourceManager.GetString("strFitColNoFit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resize columns.
        /// </summary>
        internal static string strFitColSizing {
            get {
                return ResourceManager.GetString("strFitColSizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit all columns in one page.
        /// </summary>
        internal static string strFitColZooming {
            get {
                return ResourceManager.GetString("strFitColZooming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pt..
        /// </summary>
        internal static string strFontPoint {
            get {
                return ResourceManager.GetString("strFontPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freeze Column.
        /// </summary>
        internal static string strFreezeColumn {
            get {
                return ResourceManager.GetString("strFreezeColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Data Filter.
        /// </summary>
        internal static string strHideDataFilter {
            get {
                return ResourceManager.GetString("strHideDataFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Error.
        /// </summary>
        internal static string strHideError {
            get {
                return ResourceManager.GetString("strHideError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide This Column.
        /// </summary>
        internal static string strHideThisColumn {
            get {
                return ResourceManager.GetString("strHideThisColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string strHistory {
            get {
                return ResourceManager.GetString("strHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        internal static string strInactive {
            get {
                return ResourceManager.GetString("strInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string strInformation {
            get {
                return ResourceManager.GetString("strInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Printers are installed. To install a printer, point to Settings on the Windows Start menu, click Printers, and then double-click Add Printer. Follow the instructions in the wizard..
        /// </summary>
        internal static string strInstallPrinter {
            get {
                return ResourceManager.GetString("strInstallPrinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos;  is not a valid value. Date value should be between &apos;{1}&apos; and &apos;{2}&apos;.
        /// </summary>
        internal static string strInvalidDateValueMsg {
            get {
                return ResourceManager.GetString("strInvalidDateValueMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        internal static string strLink {
            get {
                return ResourceManager.GetString("strLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string strNew {
            get {
                return ResourceManager.GetString("strNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Payor.
        /// </summary>
        internal static string strNewPayorTitle {
            get {
                return ResourceManager.GetString("strNewPayorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Filter.
        /// </summary>
        internal static string strNoFilter {
            get {
                return ResourceManager.GetString("strNoFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string strNone {
            get {
                return ResourceManager.GetString("strNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Sort.
        /// </summary>
        internal static string strNoSort {
            get {
                return ResourceManager.GetString("strNoSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice.
        /// </summary>
        internal static string strNoticeTitle {
            get {
                return ResourceManager.GetString("strNoticeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL GridEXColumnCollection reference.
        /// </summary>
        internal static string strNullGridExColumnCollectionReference {
            get {
                return ResourceManager.GetString("strNullGridExColumnCollectionReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL GridEXTable reference.
        /// </summary>
        internal static string strNullGridExTableReference {
            get {
                return ResourceManager.GetString("strNullGridExTableReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string strPaste {
            get {
                return ResourceManager.GetString("strPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string strPrint {
            get {
                return ResourceManager.GetString("strPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error encountered while trying to retrieve installed printers..
        /// </summary>
        internal static string strPrinterError {
            get {
                return ResourceManager.GetString("strPrinterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Printer installed in this machine..
        /// </summary>
        internal static string strPrinterNotInstalled {
            get {
                return ResourceManager.GetString("strPrinterNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        internal static string strQuestion {
            get {
                return ResourceManager.GetString("strQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string strRefresh {
            get {
                return ResourceManager.GetString("strRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resize Columns.
        /// </summary>
        internal static string strResizeColumns {
            get {
                return ResourceManager.GetString("strResizeColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string strSave {
            get {
                return ResourceManager.GetString("strSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and Approve.
        /// </summary>
        internal static string strSaveAndApprove {
            get {
                return ResourceManager.GetString("strSaveAndApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Column Chooser....
        /// </summary>
        internal static string strShowColumnChooser {
            get {
                return ResourceManager.GetString("strShowColumnChooser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Data Filter.
        /// </summary>
        internal static string strShowDataFilter {
            get {
                return ResourceManager.GetString("strShowDataFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Error.
        /// </summary>
        internal static string strShowError {
            get {
                return ResourceManager.GetString("strShowError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign off.
        /// </summary>
        internal static string strSignOff {
            get {
                return ResourceManager.GetString("strSignOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Ascending.
        /// </summary>
        internal static string strSortAscending {
            get {
                return ResourceManager.GetString("strSortAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Descending.
        /// </summary>
        internal static string strSortDescending {
            get {
                return ResourceManager.GetString("strSortDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnFreeze All Columns.
        /// </summary>
        internal static string strUnFreezeAllColumns {
            get {
                return ResourceManager.GetString("strUnFreezeAllColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string strView {
            get {
                return ResourceManager.GetString("strView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string strWarning {
            get {
                return ResourceManager.GetString("strWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 81, 82, 100.
        /// </summary>
        internal static string TabForeColor {
            get {
                return ResourceManager.GetString("TabForeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TopRight.
        /// </summary>
        internal static string TextAlign {
            get {
                return ResourceManager.GetString("TextAlign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segoe UI, 11, Regular.
        /// </summary>
        internal static string TitleBarFont {
            get {
                return ResourceManager.GetString("TitleBarFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 255,255,255.
        /// </summary>
        internal static string TitleBarFontColor {
            get {
                return ResourceManager.GetString("TitleBarFontColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 42, 95, 170.
        /// </summary>
        internal static string TitleColor {
            get {
                return ResourceManager.GetString("TitleColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 219,218,172.
        /// </summary>
        internal static string WorkHourBackGroundColor {
            get {
                return ResourceManager.GetString("WorkHourBackGroundColor", resourceCulture);
            }
        }
    }
}
